# ===================================================================
# Spring Boot 核心配置文件
# ===================================================================

# 服务器相关配置
server:
  port: 8080 # 定义应用的监听端口

# ===================================================================
# Spring 框架核心配置
# ===================================================================
spring:
  # -------------------------------------------------------------------
  # 数据源 (DataSource) 配置 - 连接MySQL数据库
  # -------------------------------------------------------------------
  datasource:
    # 数据库连接URL
    url: jdbc:mysql://192.168.56.1:3306/cpeDB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    # MySQL用户名
    username: cpeUsr
    # MySQL密码
    password: 123456
    # 明确指定使用哪个JDBC驱动
    driver-class-name: com.mysql.cj.jdbc.Driver

  # -------------------------------------------------------------------
  # Java Persistence API (JPA) 配置
  # -------------------------------------------------------------------
  jpa:
    # JPA的相关属性配置
    properties:
      hibernate:
        # SQL方言，帮助Hibernate生成针对特定数据库的SQL
        dialect: org.hibernate.dialect.MySQLDialect
    # Hibernate specific settings
    hibernate:
      # ddl-auto: 自动数据定义语言。
      ddl-auto: update
    # 是否在控制台显示Hibernate执行的SQL语句，便于调试
    show-sql: true

  # -------------------------------------------------------------------
  # Kafka 配置
  # -------------------------------------------------------------------
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    consumer:
      group-id: cpe-platform-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "com.cpeplatform.api.dto,com.cpeplatform.dto"
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.ms: 0

# ===================================================================
# 应用自定义配置
# ===================================================================
app:
  # Kafka Topic 名称配置
  kafka:
    topic:
      # 模拟器发送的原始数据 Topic
      raw-data: "cpe-raw-data"
      # 定义新的聚合数据 Topic
      features-for-prediction: "cpe-features-for-prediction"
      # 定义新地预测结果 Topic
      prediction-result: "cpe-prediction-result"
      # 设备状态数据的 Topic
      processed-status: "cpe-processed-status"
  # 数据模拟器配置
  simulator:
    # 是否启用数据模拟器。设置为 'false' 可以关闭它，无需修改代码。
    enabled: false

# ===================================================================
# 日志 (Logging) 配置
# ===================================================================
logging:
  level:
    # 设置根日志级别为INFO，这是默认级别
    root: INFO
    # 为您自己的项目包设置更详细的日志级别为DEBUG，方便开发调试
    com.cpeplatform: DEBUG
    # Spring框架的日志级别，设为INFO，避免过多无关日志刷屏
    org.springframework.web: INFO
    # Hibernate的日志级别，设为INFO
    org.hibernate: INFO
